(** Hashing operations. Utilizes MD5 hashing. *)

type t
(** Alias for the hash data structure. *)

val of_string : string -> t
(** [of_string s] is the hash of the string *)

val rehash : string -> t -> t
(** [rehash s h] is a new hash generated by combining string [s] with the hash
    [h] *)

val from_hex : string -> t
(** [from_hex s] is the hash represented by a 16-character hex hash. Raises:
    [Invalid_argument] is argument is not exactly 32 hexadecimal characters.*)

val to_hex : t -> string
(** [to_hex h] is the 32 character hexadecimal string representation of [h] *)

val compare : t -> t -> int
(** [compare h1 h2] compares the hex hash of [h1] and [h2] with same
    specification as [String.compare] *)

val equal : t -> t -> bool
(** [equal h1 h2] is true if the hash [h1] and [h2] are equal. *)
